### ISSUE TITLE
Suggestion: Pocketmine plugins

### ISSUE THREAD

**Issue by babbottscott** [BukGet/api#106]
Curious if there's any plan/collaboration with the pocketmine folks to make their plugins available through the api.  Would be a huge help for hosting PE servers.

**Comment by Matthww** [comment]
Would love to see this happening!

**Comment by Matthww** [comment]
https://gist.github.com/flaxues/a600ed1a44e109d6a4fb

Here are some api's from pocketmine

**Comment by SteveMcGrath** [comment]
why not just use their API?

**Comment by Matthww** [comment]
Well I don't know how :S

**Comment by Matthww** [comment]
Could you maybe help me? I want to use it in multicraft...

**Comment by SteveMcGrath** [comment]
It's not as simple as you may think to just shim it into BukGet.  There would be some API changes to support something like this, and a new parser would need to be written.

Looking into what they have there, it appears to be a simple XenForo system with the basic API enabled. 

https://github.com/Contex/XenAPI/wiki/REST-API-Actions

From what I'm seeing, in order to get anything close to what BukGet does, it would mean page scraping like we do for Bukkit, which I vowed to never do again.

**Comment by Matthww** [comment]
So to do this you need to do many things :(

**Comment by SteveMcGrath** [comment]
Yes, the XenForo API is needlessly complicated, and is incomplete for your uses.  To give you an idea of the complexity of what your asking for, let me point you to BukGet's generator code for Bukkit

https://github.com/BukGet/generator/blob/master/bukgen/bukkit.py

**Comment by DMarby** [comment]
Closing this as the project is no longer active.
