### ISSUE TITLE
Contribution Question

### ISSUE THREAD

**Issue by ethsmith** [BukGet/api#122]
I have a question and it is if I can get BukGet to work again is there a possibility of me being able to be the new maintainer and being added as an admin to the github org and the website?

**Comment by SteveMcGrath** [comment]
You would have to do significant work you the generator code to get it working again.  Further any time that BukkitDev changes their site style, you would need to modify the code to match.  Assuming you got a working generator, you would need to setup GeoDNS, and get several servers running to distribute the load globally.  Lastly, assuming you got all of this together, tools like SpiGet are out there that are working on replicating a lot of our effort for spigot.

**Comment by DMarby** [comment]
To add to what Steve said, you are of course free to fork BukGet and run your own version of it under a different name, but we don't have any interest in reviving the original BukGet or having it be maintained.

**Comment by ethsmith** [comment]
@DMarby just out of curiosity, what is the reason behind wanting the original BukGet to stay unsupported?

**Comment by SteveMcGrath** [comment]
BukGet was never intended to become the beast it became.  In all reality by providing the service that we did, the folks running things like BukkitDev never saw the need to build their own proper API.  They relied on us and didn't help us one bit.  By keeping BukGet shut, the hope is to force better 1st-party APIs instead of relying on web scraping to pull the information.

**Comment by ethsmith** [comment]
@SteveMcGrath thanks for the explanation.
